package com.how2java.smh.mapper;

import com.how2java.smh.pojo.Hero;
import com.how2java.smh.pojo.HeroExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HeroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    long countByExample(HeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    int deleteByExample(HeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    int insert(Hero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    int insertSelective(Hero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    List<Hero> selectByExample(HeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    Hero selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") Hero record, @Param("example") HeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    int updateByExample(@Param("record") Hero record, @Param("example") HeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    int updateByPrimaryKeySelective(Hero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    int updateByPrimaryKey(Hero record);
}