package com.how2java.smh.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table how2java..hero
 */
public class Hero implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column how2java..hero.id
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   英雄姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column how2java..hero.name
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    private String name;

    /**
     * Database Column Remarks:
     *   英雄血量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column how2java..hero.hp
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    private Float hp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column how2java..hero.id
     *
     * @return the value of how2java..hero.id
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column how2java..hero.id
     *
     * @param id the value for how2java..hero.id
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column how2java..hero.name
     *
     * @return the value of how2java..hero.name
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column how2java..hero.name
     *
     * @param name the value for how2java..hero.name
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column how2java..hero.hp
     *
     * @return the value of how2java..hero.hp
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    public Float getHp() {
        return hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column how2java..hero.hp
     *
     * @param hp the value for how2java..hero.hp
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    public void setHp(Float hp) {
        this.hp = hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Hero other = (Hero) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getHp() == null ? other.getHp() == null : this.getHp().equals(other.getHp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getHp() == null) ? 0 : getHp().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table how2java..hero
     *
     * @mbg.generated Sun Oct 11 15:51:34 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", hp=").append(hp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}